<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <AssemblyName>CodexVault.Cli</AssemblyName>
    <Product>Codex Vault CLI</Product>
    <AssemblyTitle>Codex Vault Command Line</AssemblyTitle>
    <Authors>Arkadiusz Pajda</Authors>
    <Copyright>Copyright © 2026 Arkadiusz Pajda</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>1.4.1</Version>
    <AssemblyVersion>1.4.1.0</AssemblyVersion>
    <FileVersion>1.4.1.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WindowsSecretManager.Core\WindowsSecretManager.Core.csproj" />
  </ItemGroup>
</Project>
